# Generated by Django 5.2.8 on 2025-11-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_line_route_line_station_line"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stop",
            name="arrival_time",
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="stop",
            name="departure_time",
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="train",
            name="number",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
