# Generated by Django 5.2.8 on 2025-11-26 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_stop_arrival_time_alter_stop_departure_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transfer_time_minutes", models.IntegerField()),
                (
                    "connection_type",
                    models.CharField(default="standard", max_length=50),
                ),
            ],
        ),
        migrations.AddField(
            model_name="station",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="line_connections",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="station",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="train",
            name="active_status",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="train",
            name="operating_days",
            field=models.CharField(
                choices=[
                    ("daily", "Daily [*]"),
                    ("no_friday", "No Friday [1]"),
                    ("friday_only", "Friday Only [2]"),
                ],
                db_index=True,
                default="daily",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="stop",
            index=models.Index(
                fields=["station", "departure_time"], name="api_stop_station_50229b_idx"
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="from_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connections_from",
                to="api.station",
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="to_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="connections_to",
                to="api.station",
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="transfer_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers",
                to="api.station",
            ),
        ),
        migrations.AddIndex(
            model_name="connection",
            index=models.Index(
                fields=["from_station", "to_station"],
                name="api_connect_from_st_ed7dd7_idx",
            ),
        ),
    ]
